jira:
  host:          https://xebialabs.atlassian.net
  api_path:      /rest/api/2
  activity_path: /activity
  login:         # Please add here your Jira user login
  password:      # Please add here your Jira user password
xld:
  login:         # Please add here your XLD admin user login
  password:      # Please add here your XLD admin user password